<?php
$ideapark_customize_mods_ver = "f7b7b3e24a7535727d049106f21f5e88";
global $ideapark_customize;
$ideapark_customize = [
"0" => [
"panel" => "header_and_menu_settings",
"title" => "General",
"controls" => [
"header_top_bar_settings_info" => [
"label" => "Header blocks",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
],
"header_type" => [
"label" => "",
"description" => "",
"type" => "hidden",
"default" => "header-type-1",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"class" => "WP_Customize_Hidden_Control",
],
"header_blocks_1" => [
"label" => "Header blocks (Desktop)",
"description" => "Enable or disable blocks, and then drag and drop blocks below to set up their order",
"type" => "checklist",
"default" => "logo=1(center-left)|menu=1(center-center)|buttons=1(center-right)|social=0|phone=0|email=0|address=0|hours=0|lang=0|other=0|login=0",
"choices" => [
"logo" => "Logo",
"menu" => "Mega Menu",
"buttons" => "Buttons",
"social" => "Social Media",
"phone" => "Phone",
"email" => "Имейл",
"address" => "Address",
"hours" => "Working Hours",
"lang" => "Language switcher",
"login" => "Login",
"other" => "Other",
],
"extra_option" => "ideapark_block_positions_1",
"sortable" => true,
"class" => "WP_Customize_Checklist_Control",
"sanitize_callback" => "sanitize_text_field",
"refresh" => ".c-header__outer--desktop",
"refresh_wrapper" => true,
"refresh_id" => "header-desktop",
],
"header_blocks_2" => [
"label" => "Header blocks (Mobile)",
"description" => "Enable or disable blocks, and then drag and drop blocks below to set up their order",
"type" => "checklist",
"default" => "phone=1|email=1|address=1|hours=1|lang=1|other=1|login=0|social=1",
"choices" => [
"social" => "Social Media",
"phone" => "Phone",
"email" => "Имейл",
"address" => "Address",
"hours" => "Working Hours",
"lang" => "Language switcher",
"login" => "Login",
"other" => "Other",
],
"sortable" => true,
"class" => "WP_Customize_Checklist_Control",
"sanitize_callback" => "sanitize_text_field",
"refresh" => ".c-header__mobile_blocks",
"refresh_wrapper" => true,
"refresh_id" => "header-mobile-blocks",
],
"header_phone" => [
"label" => "Phone",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
"refresh" => ".c-header--desktop .c-header__top-row-item--phone",
"refresh_wrapper" => true,
"refresh_id" => "header-phone",
],
"header_email" => [
"label" => "Имейл",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
"refresh" => ".c-header--desktop .c-header__top-row-item--email",
"refresh_wrapper" => true,
"refresh_id" => "header-email",
],
"header_address" => [
"label" => "Address",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
"refresh" => ".c-header--desktop .c-header__top-row-item--address",
"refresh_wrapper" => true,
"refresh_id" => "header-address",
],
"header_hours" => [
"label" => "Working hours",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
"refresh" => ".c-header--desktop .c-header__top-row-item--hours",
"refresh_wrapper" => true,
"refresh_id" => "header-hours",
],
"header_lang" => [
"label" => "Lang",
"description" => "You can use shortcodes, for example, the WPML language selection shortcode",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
"refresh" => ".c-header--desktop .c-header__top-row-item--lang",
"refresh_wrapper" => true,
"refresh_id" => "header-lang",
],
"header_other" => [
"label" => "Other",
"description" => "You can use some HTML tags and various shortcodes",
"type" => "textarea",
"sanitize_callback" => "wp_kses_post",
"default" => "",
"refresh" => ".c-header--desktop .c-header__top-row-item--other",
"refresh_wrapper" => true,
"refresh_id" => "header-other",
],
"wpml_style" => [
"label" => "Styling the WPML language selector",
"description" => "Use the shortcode [wpml_language_selector_widget] to insert the selector",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"header_desktop_settings_info" => [
"label" => "Desktop Header Settings",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
],
"header_buttons" => [
"label" => "Header buttons",
"description" => "Enable or disable button, and then drag and drop blocks below to set up their order",
"type" => "checklist",
"default" => "auth=1|search=1|wishlist=1|cart=1|custom=0",
"choices" => [
"auth" => "Auth",
"search" => "Търси",
"wishlist" => "Любими продукти",
"cart" => "Количка",
"custom" => "Custom",
],
"sortable" => true,
"class" => "WP_Customize_Checklist_Control",
"sanitize_callback" => "sanitize_text_field",
"refresh" => ".c-header__buttons",
"refresh_wrapper" => true,
"refresh_id" => "header-buttons",
],
"custom_button_info_1" => [
"html" => "<a href=\"#\" class=\"ideapark-control-focus\" data-control=\"custom_header_button_icon\">Custom button setting</a>",
"class" => "WP_Customize_HTML_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"header_buttons" => [
"0" => "search=custom=1",
],
],
],
"wishlist_is_disabled" => [
"label" => "Wishlist button is not shown because Wishlist Page is not set <a href=\"#\" class=\"ideapark-control-focus\" data-control=\"wishlist_page\">here</a>",
"class" => "WP_Customize_Warning_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"wishlist_page" => [
"0" => 0,
"1" => "",
],
],
],
"header_top_background_color" => [
"label" => "Background color",
"class" => "WP_Customize_Color_Control",
"sanitize_callback" => "sanitize_text_field",
"default" => "#ffffff",
"refresh" => false,
"refresh_css" => true,
],
"header_top_color" => [
"label" => "Text color",
"class" => "WP_Customize_Color_Control",
"sanitize_callback" => "sanitize_text_field",
"default" => "#181818",
"refresh" => false,
"refresh_css" => true,
],
"header_top_accent_color" => [
"label" => "Accent color",
"class" => "WP_Customize_Color_Control",
"sanitize_callback" => "sanitize_text_field",
"default" => "#C6AD8A",
"refresh" => false,
"refresh_css" => true,
],
"top_menu_depth" => [
"label" => "Main menu depth",
"default" => "unlim",
"type" => "radio",
"choices" => [
"1" => "1 level",
"2" => "2 level",
"3" => "3 level",
"unlim" => "Unlimited",
],
"sanitize_callback" => "sanitize_text_field",
],
"top_menu_submenu_color" => [
"label" => "Main menu popup text color",
"class" => "WP_Customize_Color_Control",
"sanitize_callback" => "sanitize_text_field",
"default" => "#000000",
"refresh_css" => true,
"refresh" => false,
],
"top_menu_submenu_bg_color" => [
"label" => "Main menu popup background color",
"class" => "WP_Customize_Color_Control",
"sanitize_callback" => "sanitize_text_field",
"default" => "#FFFFFF",
"refresh_css" => true,
"refresh" => false,
],
"top_menu_submenu_accent_color" => [
"label" => "Main menu popup accent color",
"description" => "Main accent color if empty",
"class" => "WP_Customize_Color_Control",
"sanitize_callback" => "sanitize_text_field",
"default" => "",
"refresh_css" => true,
"refresh" => false,
],
"top_menu_submenu_layout" => [
"label" => "Main menu popup layout",
"default" => "fullwidth",
"type" => "radio",
"choices" => [
"fullwidth" => "Fullwidth",
"compact" => "Compact",
],
"sanitize_callback" => "sanitize_text_field",
],
"top_menu_font_size" => [
"label" => "Font size of top-level menu items (px)",
"default" => 14,
"type" => "slider",
"sanitize_callback" => "sanitize_text_field",
"class" => "WP_Customize_Range_Control",
"min" => 12,
"max" => 25,
"step" => 1,
"refresh_css" => true,
"refresh" => false,
],
"top_menu_item_space" => [
"label" => "Space between top-level menu items (px)",
"default" => 20,
"type" => "slider",
"sanitize_callback" => "sanitize_text_field",
"class" => "WP_Customize_Range_Control",
"min" => 10,
"max" => 30,
"step" => 1,
"refresh_css" => true,
"refresh" => false,
],
"sticky_menu_desktop" => [
"label" => "Sticky menu (desktop)",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"sticky_logo_desktop_hide" => [
"label" => "Hide Logo in sticky menu (desktop)",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"sticky_menu_desktop" => [
"0" => "not_empty",
],
],
],
"sticky_logo_desktop_size" => [
"label" => "Logo width in sticky menu (Desktop)",
"default" => "105",
"type" => "slider",
"sanitize_callback" => "sanitize_text_field",
"class" => "WP_Customize_Range_Control",
"min" => 70,
"max" => 300,
"step" => 1,
"refresh" => false,
"refresh_css" => true,
"dependency" => [
"logo" => [
"0" => "not_empty",
],
"sticky_menu_desktop" => [
"0" => "not_empty",
],
"sticky_logo_desktop_hide" => [
"0" => "is_empty",
],
],
],
"sticky_logo_desktop_hide_text" => [
"label" => "Text instead of logo (Desktop)",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"sticky_menu_desktop" => [
"0" => "not_empty",
],
"sticky_logo_desktop_hide" => [
"0" => "not_empty",
],
],
],
"header_mobile_settings_info" => [
"label" => "Mobile Header Settings",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
],
"header_type_mobile" => [
"label" => "Mobile header type",
"default" => "header-type-mobile-1",
"sanitize_callback" => "sanitize_text_field",
"type" => "image-radio",
"class" => "WP_Customize_Image_Radio_Control",
"is_option" => true,
"refresh" => true,
"choices" => [
"header-type-mobile-1" => "http://fedefee.store/wp-content/themes/goldish/assets/img/header-mobile-01.png",
"header-type-mobile-2" => "http://fedefee.store/wp-content/themes/goldish/assets/img/header-mobile-02.png",
],
],
"header_logo_centered_mobile" => [
"label" => "Centered logo",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"header_type_mobile" => [
"0" => "header-type-mobile-2",
],
],
],
"header_buttons_mobile" => [
"label" => "Header buttons",
"description" => "Enable or disable button, and then drag and drop blocks below to set up their order",
"type" => "checklist",
"default" => "search=1|auth=1|wishlist=1|cart=1|custom=0",
"choices" => [
"auth" => "Auth",
"search" => "Търси",
"wishlist" => "Любими продукти",
"cart" => "Количка",
"custom" => "Custom",
],
"sortable" => true,
"class" => "WP_Customize_Checklist_Control",
"sanitize_callback" => "sanitize_text_field",
"refresh" => ".c-header__col-mobile-buttons",
"refresh_wrapper" => true,
"refresh_id" => "header-buttons-mobile",
"dependency" => [
"header_type_mobile" => [
"0" => "header-type-mobile-2",
],
],
],
"custom_button_info_2" => [
"html" => "<a href=\"#\" class=\"ideapark-control-focus\" data-control=\"custom_header_button_icon\">Custom button setting</a>",
"class" => "WP_Customize_HTML_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"header_buttons_mobile" => [
"0" => "search=custom=1",
],
],
],
"bottom_buttons_mobile_locations" => [
"label" => "Bottom buttons location",
"type" => "radio",
"sanitize_callback" => "sanitize_text_field",
"default" => "menu",
"choices" => [
"menu" => "Menu bottom",
"screen" => "Screen bottom",
],
],
"bottom_buttons_mobile" => [
"label" => "Bottom buttons",
"description" => "Enable or disable button, and then drag and drop blocks below to set up their order",
"type" => "checklist",
"default" => "search=1|auth=1|wishlist=1|cart=1|custom=0",
"choices" => [
"auth" => "Auth",
"search" => "Търси",
"wishlist" => "Любими продукти",
"cart" => "Количка",
"custom" => "Custom",
],
"sortable" => true,
"class" => "WP_Customize_Checklist_Control",
"sanitize_callback" => "sanitize_text_field",
"refresh" => ".c-header__menu-bottom",
"refresh_wrapper" => true,
"refresh_id" => "header-buttons-mobile-bottom",
],
"custom_button_info_3" => [
"html" => "<a href=\"#\" class=\"ideapark-control-focus\" data-control=\"custom_header_button_icon\">Custom button setting</a>",
"class" => "WP_Customize_HTML_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"bottom_buttons_mobile" => [
"0" => "search=custom=1",
],
],
],
"mobile_header_background_color" => [
"label" => "Header background color",
"class" => "WP_Customize_Color_Control",
"sanitize_callback" => "sanitize_text_field",
"default" => "#FFFFFF",
"refresh" => false,
"refresh_css" => true,
],
"mobile_header_color" => [
"label" => "Header text color",
"class" => "WP_Customize_Color_Control",
"sanitize_callback" => "sanitize_text_field",
"default" => "#000000",
"refresh" => false,
"refresh_css" => true,
],
"header_height_mobile" => [
"label" => "Header height (Mobile)",
"default" => 60,
"type" => "slider",
"sanitize_callback" => "sanitize_text_field",
"class" => "WP_Customize_Range_Control",
"min" => 60,
"max" => 120,
"step" => 1,
"refresh" => false,
"refresh_css" => true,
],
"sticky_menu_mobile" => [
"label" => "Sticky menu (Mobile)",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"sticky_header_height_mobile" => [
"label" => "Sticky header height (Mobile)",
"default" => 60,
"type" => "slider",
"sanitize_callback" => "sanitize_text_field",
"class" => "WP_Customize_Range_Control",
"min" => 60,
"max" => 120,
"step" => 1,
"refresh" => false,
"refresh_css" => true,
"dependency" => [
"sticky_menu_mobile" => [
"0" => "not_empty",
],
],
],
"sticky_logo_mobile_hide" => [
"label" => "Hide Logo in sticky menu (Mobile)",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"sticky_menu_mobile" => [
"0" => "not_empty",
],
],
],
"custom_header_button_info" => [
"label" => "Custom Header Button",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
],
"custom_header_icon_desc_0" => [
"html" => "You can upload font with custom icons <a target=\"_blank\" href=\"https://fedefee.store/wp-admin/themes.php?page=ideapark_fonts\" > here </a>",
"class" => "WP_Customize_HTML_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"is_font_icons_loader_on" => [
"0" => "not_empty",
],
],
],
"custom_header_button_icon" => [
"label" => "Icon",
"class" => "WP_Customize_Font_Icons_Control",
"sanitize_callback" => "sanitize_text_field",
],
"custom_header_button_title" => [
"label" => "Title",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"custom_header_button_link" => [
"label" => "Link",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"custom_header_button_new_window" => [
"label" => "Open in new window",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"custom_header_button_link" => [
"0" => "not_empty",
],
],
],
"custom_header_button_no_follow" => [
"label" => "Add nofollow",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"custom_header_button_link" => [
"0" => "not_empty",
],
],
],
"transparent_header_settings_info" => [
"label" => "Transparent header Settings",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
],
"transparent_header" => [
"label" => "Transparent header on the front page",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"transparent_header_color" => [
"label" => "Transparent header text color",
"class" => "WP_Customize_Color_Control",
"sanitize_callback" => "sanitize_text_field",
"default" => "",
"refresh" => false,
"refresh_css" => true,
"dependency" => [
"transparent_header" => [
"0" => "not_empty",
],
],
],
"transparent_header_accent_color" => [
"label" => "Transparent header accent color",
"class" => "WP_Customize_Color_Control",
"sanitize_callback" => "sanitize_text_field",
"default" => "",
"refresh" => false,
"refresh_css" => true,
"dependency" => [
"transparent_header" => [
"0" => "not_empty",
],
],
],
"logo_sticky" => [
"label" => "Transparent header logo",
"description" => "Leave empty for using main Logo",
"class" => "WP_Customize_Image_Control",
"sanitize_callback" => "sanitize_text_field",
"refresh" => true,
"dependency" => [
"logo" => [
"0" => "not_empty",
],
"transparent_header" => [
"0" => "not_empty",
],
],
],
"logo_mobile_sticky" => [
"label" => "Transparent header logo (mobile)",
"class" => "WP_Customize_Image_Control",
"sanitize_callback" => "sanitize_text_field",
"refresh" => true,
"dependency" => [
"logo_mobile" => [
"0" => "not_empty",
],
"transparent_header" => [
"0" => "not_empty",
],
],
],
"header_other_settings_info" => [
"label" => "Other Header Settings",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
],
"remove_frontpage_logo_link" => [
"label" => "Remove the link from the logo on the front page",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"custom_header_icons_info" => [
"label" => "Custom Header Icons",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"is_font_icons_loader_on" => [
"0" => "not_empty",
],
],
],
"custom_header_icon_desc" => [
"html" => "You can upload font with custom icons <a target=\"_blank\" href=\"https://fedefee.store/wp-admin/themes.php?page=ideapark_fonts\" > here </a>",
"class" => "WP_Customize_HTML_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"is_font_icons_loader_on" => [
"0" => "not_empty",
],
],
],
"custom_header_icon_search" => [
"label" => "Search icon",
"class" => "WP_Customize_Font_Icons_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"is_font_icons_loader_on" => [
"0" => "not_empty",
],
],
],
"custom_header_icon_auth" => [
"label" => "Auth icon",
"class" => "WP_Customize_Font_Icons_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"is_font_icons_loader_on" => [
"0" => "not_empty",
],
],
],
"custom_header_icon_wishlist" => [
"label" => "Wishlist icon",
"class" => "WP_Customize_Font_Icons_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"is_font_icons_loader_on" => [
"0" => "not_empty",
],
],
],
"custom_header_icon_cart" => [
"label" => "Cart icon",
"class" => "WP_Customize_Font_Icons_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"is_font_icons_loader_on" => [
"0" => "not_empty",
],
],
],
"custom_header_icon_hamburger" => [
"label" => "Hamburger icon",
"class" => "WP_Customize_Font_Icons_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"is_font_icons_loader_on" => [
"0" => "not_empty",
],
],
],
"is_font_icons_loader_on" => [
"label" => "",
"description" => "",
"type" => "hidden",
"default" => "ideapark_font_icons_loader_plugin_on",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"class" => "WP_Customize_Hidden_Control",
],
],
],
"1" => [
"panel" => "header_and_menu_settings",
"title" => "Logo",
"controls" => [
"header_desktop_logo_info" => [
"label" => "Desktop Logo Settings",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
"priority" => 90,
],
"logo" => [
"label" => "Logo",
"class" => "WP_Customize_Image_Control",
"sanitize_callback" => "sanitize_text_field",
"priority" => 91,
"refresh" => true,
],
"truncate_logo_placeholder" => [
"label" => "Truncate logo placeholder",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"logo" => [
"0" => "is_empty",
],
],
],
"logo_size" => [
"label" => "Logo max width (Desktop)",
"default" => 205,
"type" => "slider",
"sanitize_callback" => "sanitize_text_field",
"class" => "WP_Customize_Range_Control",
"min" => 70,
"max" => 300,
"step" => 1,
"priority" => 93,
"refresh_css" => ".c-header__logo--desktop",
"refresh" => false,
"dependency" => [
"logo" => [
"0" => "not_empty",
],
],
],
"header_mobile_logo_info" => [
"label" => "Mobile Logo Settings",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
"priority" => 100,
],
"logo_mobile" => [
"label" => "Logo",
"description" => "Leave empty for using desktop Logo",
"class" => "WP_Customize_Image_Control",
"sanitize_callback" => "sanitize_text_field",
"priority" => 101,
"refresh" => true,
"dependency" => [
"logo" => [
"0" => "not_empty",
],
],
],
"logo_size_mobile" => [
"label" => "Logo max width (Mobile)",
"default" => 205,
"type" => "slider",
"sanitize_callback" => "sanitize_text_field",
"class" => "WP_Customize_Range_Control",
"min" => 40,
"max" => 200,
"step" => 1,
"priority" => 103,
"refresh_css" => ".c-header__logo--mobile",
"refresh" => false,
"dependency" => [
"logo" => [
"0" => "not_empty",
],
],
],
"header_height_mobile_link" => [
"html" => "Header height you can change <a href=\"#\" class=\"ideapark-control-focus\" data-control=\"header_height_mobile\"> here </a>",
"class" => "WP_Customize_HTML_Control",
"sanitize_callback" => "sanitize_text_field",
"priority" => 104,
"dependency" => [
"logo" => [
"0" => "not_empty",
],
],
],
],
],
"2" => [
"panel" => "header_and_menu_settings",
"title" => "Live Search",
"controls" => [
"ajax_search_post_type" => [
"label" => "Search type",
"default" => "products",
"type" => "radio",
"choices" => [
"products" => "Products only",
"whole" => "Whole site",
],
"sanitize_callback" => "sanitize_text_field",
],
"ajax_search" => [
"label" => "Live search (ajax)",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"ajax_search_limit" => [
"label" => "Number of products in the live search",
"default" => 8,
"min" => 1,
"step" => 1,
"type" => "number",
"sanitize_callback" => "absint",
"dependency" => [
"ajax_search" => [
"0" => "not_empty",
],
],
],
],
],
"3" => [
"panel" => "header_and_menu_settings",
"title" => "Advert Bar",
"controls" => [
"header_advert_bar_page" => [
"label" => "HTML block to display in the Advert Bar",
"default" => 0,
"class" => "WP_Customize_HTML_Block_Control",
"sanitize_callback" => "absint",
"refresh" => ".c-header__advert_bar",
"refresh_wrapper" => true,
"refresh_id" => "header-advert-bar",
],
"header_advert_bar_placement" => [
"label" => "Advert Bar placement",
"default" => "below",
"sanitize_callback" => "sanitize_text_field",
"type" => "radio",
"choices" => [
"above" => "Above the header",
"below" => "Below the header",
],
],
],
],
"4" => [
"panel" => "header_and_menu_settings",
"title" => "Social Media Links",
"description" => "Add the full url of your social media page e.g http://twitter.com/yoursite",
"refresh" => ".c-soc",
"refresh_wrapper" => true,
"refresh_id" => "soc",
"controls" => [
"facebook" => [
"label" => "Facebook url",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"instagram" => [
"label" => "Instagram url",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"vk" => [
"label" => "VK url",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"ok" => [
"label" => "OK url",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"telegram" => [
"label" => "Telegram url",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"whatsapp" => [
"label" => "Whatsapp url",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"line" => [
"label" => "Line url",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"wechat" => [
"label" => "WeChat url",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"viber" => [
"label" => "Viber url",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"discord" => [
"label" => "Discord url",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"twitter" => [
"label" => "X (Twitter) url",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"youtube" => [
"label" => "YouTube url",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"vimeo" => [
"label" => "Vimeo url",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"snapchat" => [
"label" => "Snapchat url",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"tiktok" => [
"label" => "TikTok url",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"linkedin" => [
"label" => "LinkedIn url",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"flickr" => [
"label" => "Flickr url",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"pinterest" => [
"label" => "Pinterest url",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"tumblr" => [
"label" => "Tumblr url",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"github" => [
"label" => "Github url",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"custom_soc_icon_1" => [
"label" => "Custom icon #1",
"class" => "WP_Customize_Font_Icons_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"is_font_icons_loader_on" => [
"0" => "not_empty",
],
],
],
"custom_soc_url_1" => [
"label" => "Custom url #1",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"custom_soc_icon_2" => [
"label" => "Custom icon #2",
"class" => "WP_Customize_Font_Icons_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"is_font_icons_loader_on" => [
"0" => "not_empty",
],
],
],
"custom_soc_url_2" => [
"label" => "Custom url #2",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
],
],
"5" => [
"title" => "Blog Posts",
"panel" => "blog_settings",
"section_id" => "blog_posts",
"controls" => [
"post_layout" => [
"label" => "Blog Layout",
"type" => "radio",
"sanitize_callback" => "sanitize_text_field",
"default" => "list",
"is_option" => true,
"choices" => [
"grid" => "Grid (without sidebar)",
"list" => "List (with sidebar)",
],
],
"remove_post_breadcrumbs" => [
"label" => "Remove post title from breadcrumb",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"post_grid_list_hide_category" => [
"label" => "Hide Category",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"post_grid_list_hide_date" => [
"label" => "Hide Date",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"post_grid_list_hide_excerpt" => [
"label" => "Hide Excerpt",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
],
],
"6" => [
"title" => "Blog Page",
"panel" => "blog_settings",
"section_id" => "blog_page",
"controls" => [
"sidebar_post" => [
"label" => "Sidebar in Post",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"post_hide_category" => [
"label" => "Hide Category",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"post_hide_date" => [
"label" => "Hide Date",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"post_hide_share" => [
"label" => "Hide Share Buttons",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"post_hide_tags" => [
"label" => "Hide Tags",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"post_hide_comment" => [
"label" => "Hide Comments Info",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"post_hide_author" => [
"label" => "Hide Author Info",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"post_hide_postnav" => [
"label" => "Hide Post Navigation (Prev / Next)",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
],
],
"7" => [
"section" => "background_image",
"controls" => [
"text_color" => [
"label" => "Text color",
"class" => "WP_Customize_Color_Control",
"default" => "#181818",
"sanitize_callback" => "sanitize_text_field",
],
"accent_color" => [
"label" => "Accent color",
"class" => "WP_Customize_Color_Control",
"default" => "#C6AD8A",
"sanitize_callback" => "sanitize_text_field",
],
"accent_background_color" => [
"label" => "Accent background color",
"class" => "WP_Customize_Color_Control",
"default" => "#FDF9F2",
"sanitize_callback" => "sanitize_text_field",
],
"shadow_color_desktop" => [
"label" => "Modal window overlay color",
"class" => "WP_Customize_Color_Control",
"default" => "#FFFFFF",
"sanitize_callback" => "sanitize_text_field",
],
"hide_inner_background" => [
"label" => "Hide background on inner pages",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"priority" => 100,
],
],
],
"8" => [
"title" => "Footer",
"priority" => 120,
"controls" => [
"footer_page" => [
"label" => "HTML block to display in the footer",
"default" => 0,
"class" => "WP_Customize_HTML_Block_Control",
"sanitize_callback" => "absint",
],
"footer_copyright" => [
"label" => "Copyright",
"type" => "text",
"default" => "&copy; Copyright 2022, Goldish WordPress Theme",
"sanitize_callback" => "sanitize_text_field",
"refresh" => ".c-footer__copyright",
"refresh_id" => "footer-copyright",
"refresh_wrapper" => true,
"dependency" => [
"footer_page" => [
"0" => 0,
"1" => "",
],
],
],
],
],
"9" => [
"title" => "Fonts",
"section_id" => "fonts",
"controls" => [
"theme_font_text" => [
"label" => "Content Font (Google Font)",
"default" => "Jost",
"description" => "Default font: Jost",
"sanitize_callback" => "ideapark_sanitize_font_choice",
"type" => "select",
"choices" => "ideapark_get_font_choices",
],
"theme_font_subsets" => [
"label" => "Fonts subset (if available)",
"default" => "latin-ext",
"description" => "Default: Latin Extended",
"sanitize_callback" => "sanitize_text_field",
"type" => "select",
"choices" => "ideapark_get_google_font_subsets",
],
"capitalize_headers" => [
"label" => "Capitalize Headers",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"header_custom_fonts_info" => [
"label" => "Custom Fonts",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"is_metabox_on" => [
"0" => "not_empty",
],
],
],
"header_custom_fonts_reload" => [
"html" => "<div class=\"ideapark-reload-block\"><button type=\"button\" data-href=\"https://fedefee.store/wp-admin/customize.php?autofocus%5Bcontrol%5D=header_custom_fonts_info\" class=\"button-primary button ideapark-customizer-reload\">Reload</button>Reload the page to see the added custom fonts at the top of the font list above</div>",
"class" => "WP_Customize_HTML_Control",
"priority" => 100,
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"is_metabox_on" => [
"0" => "not_empty",
],
],
],
"is_metabox_on" => [
"label" => "",
"description" => "",
"type" => "hidden",
"default" => "ideapark_metabox_plugin_on",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"class" => "WP_Customize_Hidden_Control",
],
],
],
"10" => [
"title" => "Misc",
"controls" => [
"header_breadcrumbs" => [
"label" => "Show breadcrumbs in page header",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"sticky_sidebar" => [
"label" => "Sticky sidebar",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"disable_elementor_default_gap" => [
"label" => "Disable default column gaps in Elementor",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"disable_block_editor" => [
"label" => "Disable block editor",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"limit_fullwidth_1920" => [
"label" => "Limit fullwidth content to 1920px",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"404_empty_image" => [
"label" => "Custom icon for 404 page",
"class" => "WP_Customize_Image_Control",
"sanitize_callback" => "sanitize_text_field",
],
"cart_empty_image" => [
"label" => "Custom icon for empty cart page",
"class" => "WP_Customize_Image_Control",
"sanitize_callback" => "sanitize_text_field",
],
"wishlist_empty_image" => [
"label" => "Custom icon for empty wishlist page",
"class" => "WP_Customize_Image_Control",
"sanitize_callback" => "sanitize_text_field",
],
"share_buttons" => [
"label" => "Share buttons on the product and post pages",
"description" => "Enable or disable button, and then drag and drop tabs below to set up their order",
"type" => "checklist",
"default" => "facebook=1|twitter=1|pinterest=1|whatsapp=1|telegram=0|linkedin=0",
"choices" => [
"facebook" => "Facebook",
"telegram" => "Telegram",
"whatsapp" => "Whatsapp",
"twitter" => "X (Twitter)",
"linkedin" => "LinkedIn",
"pinterest" => "Pinterest",
],
"sortable" => true,
"class" => "WP_Customize_Checklist_Control",
"sanitize_callback" => "sanitize_text_field",
],
"to_top_button_info" => [
"label" => "Scroll To Top Button",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
],
"to_top_button" => [
"label" => "Show Button",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"to_top_button_color" => [
"label" => "Button color",
"description" => "Default color if empty",
"class" => "WP_Customize_Color_Control",
"sanitize_callback" => "sanitize_text_field",
"default" => "#C6AD8A",
"dependency" => [
"to_top_button" => [
"0" => "not_empty",
],
],
],
],
],
"11" => [
"title" => "Performance",
"description" => "Use these options to put your theme to a high speed as well as save your server resources!",
"controls" => [
"use_minified_css" => [
"label" => "Use minified CSS",
"description" => "Load all theme css files combined and minified into a single file",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"use_minified_js" => [
"label" => "Use minified JS",
"description" => "Load all theme js files combined and minified into a single file",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"load_jquery_in_footer" => [
"label" => "Load jQuery in footer",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"lazyload" => [
"label" => "Lazy load images",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"google_fonts_display_swap" => [
"label" => "Use parameter display=swap for Google Fonts",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"js_delay" => [
"label" => "Delay JavaScript execution",
"description" => "Improves performance by delaying the execution of JavaScript until user interaction (e.g. scroll, click). ",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
],
],
"12" => [
"panel" => "woocommerce",
"section_id" => "woocommerce_cart",
"title" => "Количка",
"priority" => 10,
"controls" => [
"popup_cart_layout" => [
"label" => "Pop-up Cart layout (Desktop)",
"default" => "default",
"sanitize_callback" => "sanitize_text_field",
"type" => "radio",
"choices" => [
"default" => "Default",
"sidebar" => "Sidebar",
],
],
"popup_cart_auto_open_desktop" => [
"label" => "Open the pop-up cart after adding the product (Desktop)",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"popup_cart_layout" => [
"0" => "sidebar",
],
],
],
"popup_cart_auto_open_mobile" => [
"label" => "Open the pop-up cart after adding the product (Mobile)",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"popup_cart_modal" => [
"label" => "Clicking outside the sidebar closes the cart",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"cart_auto_update" => [
"label" => "Auto update cart when quantity changed on the cart page",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"expand_coupon" => [
"label" => "Expand Coupon Code block",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
],
],
"13" => [
"panel" => "woocommerce",
"section" => "woocommerce_checkout",
"controls" => [
"expand_coupon_info" => [
"html" => "<a href=\"#\" class=\"ideapark-control-focus\" data-control=\"expand_coupon\">Expand Coupon Code block</a>",
"class" => "WP_Customize_HTML_Control",
"sanitize_callback" => "sanitize_text_field",
"priority" => 100,
],
],
],
"14" => [
"panel" => "woocommerce",
"section" => "woocommerce_store_notice",
"controls" => [
"store_notice_info" => [
"html" => "Use <a href=\"#\" class=\"ideapark-control-focus\" data-control=\"header_advert_bar_page\"> Advert Bar </a>  instead of Store Notice to place ads created in Elementor above or below the header.",
"class" => "WP_Customize_HTML_Control",
"sanitize_callback" => "sanitize_text_field",
"priority" => 5,
],
"store_notice" => [
"label" => "Store notice placement",
"default" => "top",
"sanitize_callback" => "sanitize_text_field",
"type" => "radio",
"priority" => 50,
"choices" => [
"top" => "At the top of the page",
"bottom" => "At the bottom of the screen (fixed)",
],
"dependency" => [
"woocommerce_demo_store" => [
"0" => "not_empty",
],
],
],
"store_notice_button_hide" => [
"label" => "Hide button",
"priority" => 51,
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"woocommerce_demo_store" => [
"0" => "not_empty",
],
],
],
"store_notice_button_text" => [
"label" => "Store notice custom button text",
"description" => "Default if empty",
"type" => "text",
"priority" => 51,
"default" => "",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"store_notice_button_hide" => [
"0" => "is_empty",
],
"woocommerce_demo_store" => [
"0" => "not_empty",
],
],
],
"store_notice_color" => [
"label" => "Store notice text color ",
"class" => "WP_Customize_Color_Control",
"sanitize_callback" => "sanitize_text_field",
"default" => "#FFFFFF",
"priority" => 52,
"dependency" => [
"woocommerce_demo_store" => [
"0" => "not_empty",
],
],
],
"store_notice_background_color" => [
"label" => "Store notice background color",
"class" => "WP_Customize_Color_Control",
"sanitize_callback" => "sanitize_text_field",
"default" => "#CF3540",
"priority" => 53,
"dependency" => [
"woocommerce_demo_store" => [
"0" => "not_empty",
],
],
],
],
],
"15" => [
"panel" => "woocommerce",
"title" => "General",
"priority" => 0,
"section_id" => "woocommerce",
"controls" => [
"disable_purchase" => [
"label" => "Disable purchase",
"description" => "Completely disables the ability to order products, turning the site into a showcase of goods.",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"hide_prices" => [
"label" => "Hide prices",
"description" => "Hide prices in the grid and on the product page.",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"search_by_sku" => [
"label" => "Search by SKU",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"search_by_category" => [
"label" => "Search by Category name",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"search_by_tag" => [
"label" => "Search by Tag name",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"search_by_brand_info" => [
"html" => "<a href=\"#\" class=\"ideapark-control-focus\" data-control=\"search_by_brand\"> Search by Brand name </a>",
"class" => "WP_Customize_HTML_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"product_brand_attribute" => [
"0" => "not_empty",
],
],
],
"hide_uncategorized" => [
"label" => "Hide Uncategorized (default) category",
"description" => "Products will be available only by direct link",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"hidden_product_category" => [
"label" => "Hide category with products",
"description" => "Products will be available only by direct link",
"default" => 0,
"class" => "WP_Customize_Product_Categories_Control",
"sanitize_callback" => "absint",
],
"register_page" => [
"label" => "Страница за регистрация",
"description" => "Select a page with a custom registration form, if you use it instead of the standard registration form.",
"default" => 0,
"class" => "WP_Customize_Page_Control",
"sanitize_callback" => "absint",
],
"maintenance_mode_page" => [
"label" => "Coming soon page",
"description" => "Select the page that will be displayed when “Coming soon” is enabled in the WooCommerce settings.",
"default" => 0,
"class" => "WP_Customize_Page_Control",
"sanitize_callback" => "absint",
],
],
],
"16" => [
"panel" => "woocommerce",
"title" => "Product Grid",
"priority" => 2,
"section_id" => "woocommerce_grid",
"controls" => [
"products_per_page" => [
"label" => "Products per page",
"default" => 12,
"min" => 1,
"step" => 1,
"class" => "WP_Customize_Number_Control",
"type" => "number",
"sanitize_callback" => "absint",
"priority" => 1,
],
"product_grid_pagination" => [
"label" => "Paging",
"default" => "pagination",
"sanitize_callback" => "sanitize_text_field",
"type" => "radio",
"choices" => [
"pagination" => "Pagination",
"loadmore" => "Load More",
"infinity" => "Infinity",
],
"priority" => 1,
],
"product_grid_load_more_text" => [
"label" => "Load More button text",
"type" => "text",
"default" => "Load More",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"product_grid_pagination" => [
"0" => "loadmore",
],
],
"priority" => 1,
],
"show_subcat_in_header" => [
"label" => "Show subcategories in Page header",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"priority" => 1,
],
"show_subcat_in_header_nav" => [
"label" => "Show navigation arrows in the subcategories carousel on mobile and tablet",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"priority" => 1,
"dependency" => [
"show_subcat_in_header" => [
"0" => "not_empty",
],
],
],
"subcat_in_header_layout" => [
"label" => "Subcategories layout",
"default" => "round",
"type" => "radio",
"priority" => 1,
"choices" => [
"round" => "Round",
"square" => "Square",
],
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"show_subcat_in_header" => [
"0" => "not_empty",
],
],
],
"shop_sidebar" => [
"label" => "Show sidebar",
"description" => "If this option is disabled, the sidebar is displayed as a pop-up filter.",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"single_sidebar" => [
"label" => "Single sidebar for mobile and desktop versions",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"is_option" => true,
],
"shop_sidebar_modal" => [
"label" => "Clicking outside the popup filter closes it",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"product_grid_layout" => [
"label" => "Grid layout (Desktop)",
"default" => "4-per-row",
"sanitize_callback" => "sanitize_text_field",
"type" => "radio",
"choices" => [
"2-per-row" => "2 per row",
"3-per-row" => "3 per row",
"4-per-row" => "4 per row",
"compact" => "compact",
],
],
"product_grid_text_desktop" => [
"label" => "Text placement (Desktop)",
"default" => "below",
"sanitize_callback" => "sanitize_text_field",
"type" => "radio",
"choices" => [
"above" => "Above the image",
"below" => "Below the image",
],
"dependency" => [
"product_grid_layout" => [
"0" => "2-per-row",
"1" => "3-per-row",
"2" => "4-per-row",
],
],
],
"product_grid_width" => [
"label" => "Grid width (Desktop)",
"default" => "fullwidth",
"sanitize_callback" => "sanitize_text_field",
"type" => "radio",
"choices" => [
"fullwidth" => "Fullwidth",
"boxed" => "Boxed",
],
],
"product_buttons_layout" => [
"label" => "Buttons Layout",
"default" => "buttons-2",
"sanitize_callback" => "sanitize_text_field",
"type" => "image-radio",
"class" => "WP_Customize_Image_Radio_Control",
"is_option" => true,
"choices" => [
"buttons-1" => "http://fedefee.store/wp-content/themes/goldish/assets/img/buttons-01.png",
"buttons-2" => "http://fedefee.store/wp-content/themes/goldish/assets/img/buttons-02.png",
],
],
"product_grid_layout_mobile" => [
"label" => "Grid layout (Mobile)",
"default" => "1-per-row-mobile",
"sanitize_callback" => "sanitize_text_field",
"type" => "radio",
"choices" => [
"1-per-row-mobile" => "1 per row",
"2-per-row-mobile" => "2 per row",
"compact-mobile" => "compact",
],
],
"product_grid_text_mobile" => [
"label" => "Text placement (Mobile)",
"default" => "below-mobile",
"sanitize_callback" => "sanitize_text_field",
"type" => "radio",
"choices" => [
"above-mobile" => "Above the image",
"below-mobile" => "Below the image",
],
"dependency" => [
"product_grid_layout_mobile" => [
"0" => "1-per-row-mobile",
"1" => "2-per-row-mobile",
],
],
],
"wishlist_grid_button" => [
"label" => "Show \"Add to wishlist\" button",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"shop_modal" => [
"label" => "Show \"Quick view\" button",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"hide_add_to_cart_mobile_2_per_row" => [
"label" => "Hide \"Quick view\" and \"Add to wishlist\" buttons in the product grid on a mobile device",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"product_grid_layout_mobile" => [
"0" => "1-per-row-mobile",
"1" => "2-per-row-mobile",
],
],
],
"hide_add_to_cart_mobile_compact" => [
"label" => "Hide \"Add to cart\", \"Quick view\" and \"Add to wishlist\" buttons in the product on a mobile device",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"product_grid_layout_mobile" => [
"0" => "compact-mobile",
],
],
],
"shop_category" => [
"label" => "Show categories",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"show_add_to_cart" => [
"label" => "Show \"Add to cart\" button",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"product_short_description" => [
"label" => "Show product short description",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"short_description_link" => [
"label" => "Short description with a link",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"product_short_description" => [
"0" => "not_empty",
],
],
],
"product_preview_rating" => [
"label" => "Show star rating in the product list",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"product_preview_number" => [
"label" => "Show number of comments",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"product_preview_rating" => [
"0" => "not_empty",
],
],
],
"star_rating_color" => [
"label" => "Star rating color",
"class" => "WP_Customize_Color_Control",
"default" => "#FFBB54",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"product_preview_rating" => [
"0" => "not_empty",
],
],
],
"show_color_variations" => [
"label" => "Show color variations",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"is_swatches_on" => [
"0" => "not_empty",
],
],
],
"hide_single_color_variations" => [
"label" => "Hide color variations if only one color",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"is_swatches_on" => [
"0" => "not_empty",
],
"show_color_variations" => [
"0" => "not_empty",
],
],
],
"product_color_attribute" => [
"label" => "Color attribute",
"description" => "Select the attribute of the product with the type `Color` or `Image`",
"type" => "select",
"sanitize_callback" => "sanitize_text_field",
"choices" => "ideapark_get_color_attributes",
"dependency" => [
"show_color_variations" => [
"0" => "not_empty",
],
"is_swatches_on" => [
"0" => "not_empty",
],
],
],
"color_variations_size" => [
"label" => "Color variations size",
"default" => 16,
"type" => "slider",
"sanitize_callback" => "sanitize_text_field",
"class" => "WP_Customize_Range_Control",
"min" => 12,
"max" => 50,
"step" => 1,
"refresh_css" => true,
"refresh" => false,
"dependency" => [
"is_swatches_on" => [
"0" => "not_empty",
],
"show_color_variations" => [
"0" => "not_empty",
],
],
],
"is_swatches_on" => [
"label" => "",
"description" => "",
"type" => "hidden",
"default" => "ideapark_swatches_plugin_on",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"class" => "WP_Customize_Hidden_Control",
],
"category_description_position" => [
"label" => "Position of the category description",
"default" => "below",
"sanitize_callback" => "sanitize_text_field",
"type" => "radio",
"choices" => [
"above" => "Above the product grid",
"below" => "Below the product grid",
],
],
"product_font_size" => [
"label" => "Title Font Size (px)",
"description" => "Excluding Compact Layout",
"default" => 24,
"type" => "slider",
"sanitize_callback" => "sanitize_text_field",
"class" => "WP_Customize_Range_Control",
"min" => 12,
"max" => 30,
"step" => 1,
"refresh_css" => true,
"refresh" => false,
],
"product_font_size_compact" => [
"label" => "Title Font Size (px)",
"description" => "Compact layout",
"default" => 18,
"type" => "slider",
"sanitize_callback" => "sanitize_text_field",
"class" => "WP_Customize_Range_Control",
"min" => 12,
"max" => 25,
"step" => 1,
"refresh_css" => true,
"refresh" => false,
],
"grid_image_info" => [
"label" => "Product Image",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
],
"grid_image_fit" => [
"label" => "Image fit",
"default" => "cover",
"sanitize_callback" => "sanitize_text_field",
"type" => "image-radio",
"class" => "WP_Customize_Image_Radio_Control",
"is_option" => true,
"choices" => [
"cover" => "http://fedefee.store/wp-content/themes/goldish/assets/img/thumb-cover.png",
"contain" => "http://fedefee.store/wp-content/themes/goldish/assets/img/thumb-contain.png",
],
],
"grid_image_prop" => [
"label" => "Image aspect ratio (height / width)",
"default" => 1,
"type" => "slider",
"sanitize_callback" => "sanitize_text_field",
"class" => "WP_Customize_Range_Control",
"min" => 0.4,
"max" => 2,
"step" => 0.05,
],
"switch_image_on_hover" => [
"label" => "Switch image on hover",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"product_buttons_layout" => [
"0" => "buttons-2",
],
"product_grid_layout" => [
"0" => "2-per-row",
"1" => "3-per-row",
"2" => "4-per-row",
],
],
],
"quickview_product_zoom" => [
"label" => "Images zoom on touch or mouseover in Quick view",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"shop_modal" => [
"0" => "not_empty",
],
],
],
"quickview_product_zoom_mobile_hide" => [
"label" => "Hide zoom on mobile (quick view)",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"quickview_product_zoom" => [
"0" => "not_empty",
],
],
],
"is_woocommerce_on" => [
"label" => "",
"description" => "",
"type" => "hidden",
"default" => "ideapark_woocommerce_on",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"class" => "WP_Customize_Hidden_Control",
],
],
],
"17" => [
"panel" => "woocommerce",
"section_id" => "woocommerce_product_page",
"title" => "Product Page",
"priority" => 2,
"controls" => [
"product_page_layout" => [
"label" => "Product Page Layout",
"default" => "layout-1",
"sanitize_callback" => "sanitize_text_field",
"type" => "radio",
"choices" => [
"layout-1" => "Classic",
"layout-2" => "Goldish",
"layout-3" => "Modern",
],
],
"product_category_carousel" => [
"label" => "Show category carousel",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"remove_product_breadcrumbs" => [
"label" => "Remove product name from breadcrumb",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"product_page_blocks_layout-1" => [
"label" => "Product Page Blocks",
"description" => "Enable or disable blocks, and then drag and drop blocks below to set up their order",
"type" => "checklist",
"default" => "ideapark_product_page_blocks_order",
"choices" => "ideapark_product_page_blocks_1",
"sortable" => true,
"class" => "WP_Customize_Checklist_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"product_page_layout" => [
"0" => "layout-1",
],
],
],
"product_page_blocks_layout-2" => [
"label" => "Product page blocks",
"description" => "Enable or disable blocks, and then drag and drop blocks below to set up their order",
"type" => "checklist",
"default" => "ideapark_product_page_blocks_order",
"choices" => "ideapark_product_page_blocks_2",
"sortable" => true,
"class" => "WP_Customize_Checklist_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"product_page_layout" => [
"0" => "layout-2",
],
],
],
"product_page_blocks_layout-3" => [
"label" => "Product page blocks",
"description" => "Enable or disable blocks, and then drag and drop blocks below to set up their order",
"type" => "checklist",
"default" => "ideapark_product_page_blocks_order",
"choices" => "ideapark_product_page_blocks_3",
"sortable" => true,
"class" => "WP_Customize_Checklist_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"product_page_layout" => [
"0" => "layout-3",
],
],
],
"product_page_blocks_reload" => [
"html" => "<div class=\"ideapark-reload-block\"><button type=\"button\" data-href=\"https://fedefee.store/wp-admin/customize.php?autofocus%5Bcontrol%5D=product_page_layout\" class=\"button-primary button ideapark-customizer-reload\">Reload</button>Reload the page if you have changed the product page layout and the above block list is empty</div>",
"class" => "WP_Customize_HTML_Control",
"sanitize_callback" => "sanitize_text_field",
],
"product_gallery_layout" => [
"label" => "Gallery Layout (Mobile)",
"default" => "desktop",
"sanitize_callback" => "sanitize_text_field",
"type" => "radio",
"choices" => [
"desktop" => "Desktop like",
"carousel" => "Carousel",
],
"dependency" => [
"product_page_layout" => [
"0" => "layout-2",
],
],
],
"product_summary_background_color" => [
"label" => "Summary section background color",
"class" => "WP_Customize_Color_Control",
"sanitize_callback" => "sanitize_text_field",
"default" => "#FDF9F2",
"dependency" => [
"product_page_layout" => [
"0" => "layout-3",
],
],
],
"product_tabs_layout" => [
"label" => "Product Tabs Layout",
"default" => "tabs-compact",
"sanitize_callback" => "sanitize_text_field",
"type" => "radio",
"choices" => [
"tabs-compact" => "Compact",
"tabs-fullwidth" => "Fullwidth",
"tabs-expanded" => "Expanded",
],
"dependency" => [
"product_page_layout" => [
"0" => "layout-1",
],
],
],
"product_tabs" => [
"label" => "Product Tabs (Default)",
"description" => "Enable or disable tab, and then drag and drop tabs below to set up their order",
"type" => "checklist",
"default" => "description=1|additional_information=1|reviews=1",
"choices" => [
"description" => "Описание",
"additional_information" => "Допълнителна информация",
"reviews" => "Отзиви",
"html_block" => "HTML block",
],
"sortable" => true,
"class" => "WP_Customize_Checklist_Control",
"sanitize_callback" => "sanitize_text_field",
],
"description_tab_header" => [
"label" => "Custom header of the \"Description\" tab",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"product_tabs" => [
"0" => "search=description=1",
],
],
],
"additional_information_tab_header" => [
"label" => "Custom header of the \"Additional information\" tab",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"product_tabs" => [
"0" => "search=additional_information=1",
],
],
],
"additional_tab_layout" => [
"label" => "Layout for Additional Information tab",
"default" => "inline",
"sanitize_callback" => "sanitize_text_field",
"type" => "radio",
"choices" => [
"inline" => "Inline",
"table" => "Table",
],
"dependency" => [
"product_tabs" => [
"0" => "search=additional_information=1",
],
],
],
"expand_tab_mobile" => [
"label" => "Expand tabs on mobile",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"product_page_layout" => [
"0" => "layout-1",
],
"product_tabs_layout" => [
"0" => "tabs-fullwidth",
],
],
],
"expand_first_tab" => [
"label" => "Expand first tab",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"product_page_layout" => [
"0" => "layout-1",
"1" => "layout-2",
],
"product_tabs_layout" => [
"0" => "tabs-compact",
],
],
],
"product_share" => [
"label" => "Show share buttons",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"hide_variable_price_range" => [
"label" => "Hide price range in the variable product",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"hide_stock_info" => [
"label" => "Hide stock quantity",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"hide_sku" => [
"label" => "Hide SKU",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"sticky_add_to_cart" => [
"label" => "Sticky Add To Cart (Mobile)",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"product_page_ajax_add_to_cart" => [
"label" => "Ajax Add to Cart",
"description" => "This option will enable the Ajax add to cart functionality on a product page. WooCommerce doesn`t have this option built-in, so theme implementation might not be compatible with a certain plugin you`re using, so it would be best to keep it disabled.",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"product_video_position" => [
"label" => "Position of the product video in thumbnails",
"type" => "select",
"sanitize_callback" => "sanitize_text_field",
"default" => 4,
"choices" => [
"1" => "1",
"2" => "2",
"3" => "3",
"4" => "4",
],
],
"product_bottom_page" => [
"label" => "HTML block to display at the bottom of the product page",
"default" => 0,
"class" => "WP_Customize_HTML_Block_Control",
"sanitize_callback" => "absint",
],
"product_page_font_size_desktop" => [
"label" => "Title Font Size (Desktop)",
"default" => 45,
"type" => "slider",
"sanitize_callback" => "sanitize_text_field",
"class" => "WP_Customize_Range_Control",
"min" => 16,
"max" => 60,
"step" => 1,
"refresh_css" => true,
"refresh" => false,
],
"product_page_font_size_mobile" => [
"label" => "Title Font Size (Mobile)",
"default" => 40,
"type" => "slider",
"sanitize_callback" => "sanitize_text_field",
"class" => "WP_Customize_Range_Control",
"min" => 16,
"max" => 50,
"step" => 1,
"refresh_css" => true,
"refresh" => false,
],
"product_image_info" => [
"label" => "Product Image",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
],
"product_image_fit" => [
"label" => "Image fit",
"default" => "cover",
"sanitize_callback" => "sanitize_text_field",
"type" => "image-radio",
"class" => "WP_Customize_Image_Radio_Control",
"is_option" => true,
"choices" => [
"cover" => "http://fedefee.store/wp-content/themes/goldish/assets/img/thumb-cover.png",
"contain" => "http://fedefee.store/wp-content/themes/goldish/assets/img/thumb-contain.png",
],
],
"product_image_prop" => [
"label" => "Image aspect ratio (height / width)",
"default" => 1,
"type" => "slider",
"sanitize_callback" => "sanitize_text_field",
"class" => "WP_Customize_Range_Control",
"min" => 0.4,
"max" => 2,
"step" => 0.05,
],
"product_image_background_color" => [
"label" => "Image block background color",
"description" => "Transparent if empty",
"class" => "WP_Customize_Color_Control",
"sanitize_callback" => "sanitize_text_field",
"default" => "#F7F7F7",
],
"shop_product_modal" => [
"label" => "Images modal gallery",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"product_inline_video" => [
"label" => "Inline video",
"description" => "Video playback on the product page. Supported formats: mp4, m4v, webm, ogv, flv. Autoplay, looped, muted, without controls.",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"shop_product_zoom" => [
"label" => "Images zoom on touch or mouseover on product page",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"shop_product_zoom_mobile_hide" => [
"label" => "Hide zoom on mobile (product page)",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"shop_product_zoom" => [
"0" => "not_empty",
],
],
],
"product_page_custom_html_info" => [
"label" => "Custom HTML",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"product_page_blocks" => [
"0" => "search!=ideapark_product_custom_html=0",
],
],
],
"product_page_custom_html" => [
"label" => "Content",
"type" => "text_editor",
"default" => "",
"sanitize_callback" => "wp_kses_post",
"class" => "WP_Customize_Text_Editor_Control",
"dependency" => [
"product_page_blocks" => [
"0" => "search!=ideapark_product_custom_html=0",
],
],
],
"product_html_text_color" => [
"label" => "Text color",
"class" => "WP_Customize_Color_Control",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"product_page_blocks" => [
"0" => "search!=ideapark_product_custom_html=0",
],
],
],
"product_html_background_color" => [
"label" => "Background color",
"class" => "WP_Customize_Color_Control",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"product_page_blocks" => [
"0" => "search!=ideapark_product_custom_html=0",
],
],
],
"product_html_border" => [
"label" => "Show border",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"product_page_blocks" => [
"0" => "search!=ideapark_product_custom_html=0",
],
],
],
"product_html_border_color" => [
"label" => "Border color",
"class" => "WP_Customize_Color_Control",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"product_html_border" => [
"0" => "not_empty",
],
"product_page_blocks" => [
"0" => "search!=ideapark_product_custom_html=0",
],
],
],
"product_html_2_col" => [
"label" => "Two-column lists",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"product_page_blocks" => [
"0" => "search!=ideapark_product_custom_html=0",
],
],
],
"product_features_info" => [
"label" => "Features",
"description" => "Displayed on the product page",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"is_metabox_on" => [
"0" => "not_empty",
],
],
],
"product_features_icon_desc" => [
"html" => "You can upload font with custom icons <a target=\"_blank\" href=\"https://fedefee.store/wp-admin/themes.php?page=ideapark_fonts\" > here </a>",
"class" => "WP_Customize_HTML_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"is_font_icons_loader_on" => [
"0" => "not_empty",
],
],
],
"product_features_text_color" => [
"label" => "Text color",
"class" => "WP_Customize_Color_Control",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
"priority" => 100,
],
"product_features_description_color" => [
"label" => "Description color",
"class" => "WP_Customize_Color_Control",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
"priority" => 100,
],
"product_features_background_color" => [
"label" => "Background color",
"class" => "WP_Customize_Color_Control",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
"priority" => 100,
],
"product_features_border" => [
"label" => "Show border",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"priority" => 100,
],
"product_features_border_color" => [
"label" => "Border color",
"class" => "WP_Customize_Color_Control",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
"priority" => 100,
"dependency" => [
"product_features_border" => [
"0" => "not_empty",
],
],
],
],
],
"18" => [
"panel" => "woocommerce",
"section_id" => "woocommerce_shop_page",
"title" => "Shop Page",
"priority" => 4,
"controls" => [
"is_shop_configured" => [
"label" => "",
"description" => "",
"type" => "hidden",
"default" => "ideapark_is_shop_configured",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"class" => "WP_Customize_Hidden_Control",
],
"shop_is_not_configured" => [
"label" => "Shop Page is not configured <a href=\"https://fedefee.store/wp-admin/admin.php?page=wc-settings&#038;tab=products\">here</a>",
"class" => "WP_Customize_Warning_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"is_shop_configured" => [
"0" => 0,
"1" => "",
],
],
],
"shop_html_block_top" => [
"label" => "HTML block (top)",
"default" => 0,
"class" => "WP_Customize_HTML_Block_Control",
"sanitize_callback" => "absint",
"dependency" => [
"is_shop_configured" => [
"0" => "not_empty",
],
],
],
"shop_html_block_bottom" => [
"label" => "HTML block (bottom)",
"default" => 0,
"class" => "WP_Customize_HTML_Block_Control",
"sanitize_callback" => "absint",
"dependency" => [
"is_shop_configured" => [
"0" => "not_empty",
],
],
],
"shop_html_block_first_page" => [
"label" => "Show HTML blocks only on the first page",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"is_shop_configured" => [
"0" => "not_empty",
],
],
],
"shop_top_block_above" => [
"label" => "Show top block above the shop content",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"is_shop_configured" => [
"0" => "not_empty",
],
],
],
],
],
"19" => [
"panel" => "woocommerce",
"section_id" => "woocommerce_brands",
"title" => "Brands",
"priority" => 4,
"controls" => [
"product_brand_attribute" => [
"label" => "Brand attribute",
"type" => "select",
"sanitize_callback" => "sanitize_text_field",
"choices" => "ideapark_get_all_attributes",
"is_option" => true,
],
"show_product_grid_brand" => [
"label" => "Show Brand in grid",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"product_brand_attribute" => [
"0" => "not_empty",
],
],
],
"show_product_page_brand" => [
"label" => "Show Brand on product page",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"product_brand_attribute" => [
"0" => "not_empty",
],
],
],
"hide_brand_additional_tab" => [
"label" => "Hide Brand in \"Additional information\" tab of the product page",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"product_brand_attribute" => [
"0" => "not_empty",
],
],
],
"show_product_page_brand_logo" => [
"label" => "Show Brand logo on product page",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"product_brand_attribute" => [
"0" => "not_empty",
],
"show_product_page_brand" => [
"0" => "not_empty",
],
],
],
"show_cart_page_brand" => [
"label" => "Show Brand on cart page",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"product_brand_attribute" => [
"0" => "not_empty",
],
],
],
"search_by_brand" => [
"label" => "Search by Brand name",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"product_brand_attribute" => [
"0" => "not_empty",
],
],
],
"brands_page" => [
"label" => "Brands page",
"description" => "Page with a list of brands. Used in breadcrumbs",
"default" => 0,
"class" => "WP_Customize_Page_Control",
"sanitize_callback" => "absint",
"dependency" => [
"product_brand_attribute" => [
"0" => "not_empty",
],
],
],
],
],
"20" => [
"panel" => "woocommerce",
"section_id" => "woocommerce_badges",
"title" => "Badges",
"priority" => 4,
"controls" => [
"outofstock_badge_info" => [
"label" => "Out of stock",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
],
"outofstock_badge_color" => [
"label" => "Out of stock badge color",
"class" => "WP_Customize_Color_Control",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"outofstock_badge_text" => [
"label" => "Out of stock text",
"description" => "Disabled if empty",
"type" => "text",
"default" => "Out of stock",
"sanitize_callback" => "sanitize_text_field",
],
"featured_badge_info" => [
"label" => "Featured",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
],
"featured_badge_color" => [
"label" => "Featured badge color",
"class" => "WP_Customize_Color_Control",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"featured_badge_text" => [
"label" => "Featured badge text",
"description" => "Disabled if empty",
"type" => "text",
"default" => "Featured",
"sanitize_callback" => "sanitize_text_field",
],
"sale_badge_info" => [
"label" => "Разпродажба",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
],
"sale_badge_color" => [
"label" => "Sale badge color",
"class" => "WP_Customize_Color_Control",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"sale_badge_text" => [
"label" => "Sale badge text",
"description" => "Disabled if empty",
"type" => "text",
"default" => "Разпродажба",
"sanitize_callback" => "sanitize_text_field",
],
"sale_badge_layout" => [
"label" => "Покажи",
"default" => "percentage",
"type" => "radio",
"choices" => [
"percentage" => "Percentage",
"text" => "Text",
],
"sanitize_callback" => "sanitize_text_field",
],
"new_badge_info" => [
"label" => "New",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
],
"new_badge_color" => [
"label" => "New badge color",
"class" => "WP_Customize_Color_Control",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"new_badge_text" => [
"label" => "New badge text",
"description" => "Disabled if empty",
"type" => "text",
"default" => "New",
"sanitize_callback" => "sanitize_text_field",
],
"product_newness" => [
"label" => "Product newness",
"description" => "Display the New badge for how many days? Set 0 for disable `NEW` badge.",
"default" => 5,
"min" => 1,
"step" => 1,
"class" => "WP_Customize_Number_Control",
"type" => "number",
"sanitize_callback" => "absint",
],
],
],
"21" => [
"panel" => "woocommerce",
"section_id" => "woocommerce_wishlist",
"title" => "Любими продукти",
"priority" => 4,
"controls" => [
"wishlist_page" => [
"label" => "Wishlist page",
"description" => "Deselect to disable wishlist",
"default" => 0,
"class" => "WP_Customize_Page_Control",
"sanitize_callback" => "absint",
],
"wishlist_share" => [
"label" => "Wishlist share buttons",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"wishlist_page" => [
"0" => "not_empty",
],
],
],
],
],
"22" => [
"panel" => "woocommerce",
"section_id" => "woocommerce_related",
"title" => "Related products, Up-Sells, Cross-Sells, Recently viewed",
"priority" => 4,
"controls" => [
"related_settings_info" => [
"label" => "Related products, Up-Sells, Cross-Sells",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
],
"related_product_show" => [
"label" => "Show related products",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"related_product_number" => [
"label" => "Number of related products",
"default" => 4,
"min" => 0,
"step" => 1,
"class" => "WP_Customize_Number_Control",
"type" => "number",
"sanitize_callback" => "absint",
"dependency" => [
"related_product_show" => [
"0" => "not_empty",
],
],
],
"related_product_header" => [
"label" => "Related products custom header",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"related_product_show" => [
"0" => "not_empty",
],
],
],
"upsells_product_header" => [
"label" => "Up-Sells custom header",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"cross_sells_product_header" => [
"label" => "Cross-Sells custom header",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"related_grid_layout" => [
"label" => "Grid layout (Desktop)",
"default" => "default",
"sanitize_callback" => "sanitize_text_field",
"type" => "select",
"choices" => [
"default" => "Default",
"2-per-row" => "2 per row",
"3-per-row" => "3 per row",
"4-per-row" => "4 per row",
"compact" => "compact",
],
],
"hide_related_short_description" => [
"label" => "Hide product short description",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"product_short_description" => [
"0" => "not_empty",
],
],
],
"recently_settings_info" => [
"label" => "Скоро разглеждани",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
],
"recently_enabled" => [
"label" => "Enable recently viewed products",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"recently_product_number" => [
"label" => "Number of products",
"default" => 4,
"min" => 0,
"step" => 1,
"class" => "WP_Customize_Number_Control",
"type" => "number",
"sanitize_callback" => "absint",
"dependency" => [
"recently_enabled" => [
"0" => "not_empty",
],
],
],
"recently_product_show" => [
"label" => "Show on Product page",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"recently_enabled" => [
"0" => "not_empty",
],
],
],
"recently_shop_show" => [
"label" => "Show on Shop page",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"recently_enabled" => [
"0" => "not_empty",
],
],
],
"recently_cart_show" => [
"label" => "Show on Cart page",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"recently_enabled" => [
"0" => "not_empty",
],
],
],
"recently_product_header" => [
"label" => "Custom header",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"recently_enabled" => [
"0" => "not_empty",
],
],
],
"recently_position" => [
"label" => "Position",
"default" => "above",
"sanitize_callback" => "sanitize_text_field",
"type" => "select",
"choices" => [
"above" => "Above other sections",
"below" => "Below other sections",
],
"dependency" => [
"recently_enabled" => [
"0" => "not_empty",
],
],
],
"recently_grid_layout" => [
"label" => "Grid layout (Desktop)",
"default" => "default",
"sanitize_callback" => "sanitize_text_field",
"type" => "select",
"choices" => [
"default" => "Default",
"2-per-row" => "2 per row",
"3-per-row" => "3 per row",
"4-per-row" => "4 per row",
"compact" => "compact",
],
"dependency" => [
"recently_enabled" => [
"0" => "not_empty",
],
],
],
"hide_recently_short_description" => [
"label" => "Hide product short description",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"recently_enabled" => [
"0" => "not_empty",
],
"product_short_description" => [
"0" => "not_empty",
],
],
],
"last_option" => [
"label" => "",
"description" => "",
"type" => "hidden",
"default" => "",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"class" => "WP_Customize_Hidden_Control",
],
],
],
];

global $ideapark_customize_mods_def;
$ideapark_customize_mods_def = [
"header_type" => "header-type-1",
"header_blocks_1" => "logo=1(center-left)|menu=1(center-center)|buttons=1(center-right)|social=0|phone=0|email=0|address=0|hours=0|lang=0|other=0|login=0",
"header_blocks_2" => "phone=1|email=1|address=1|hours=1|lang=1|other=1|login=0|social=1",
"header_phone" => "",
"header_email" => "",
"header_address" => "",
"header_hours" => "",
"header_lang" => "",
"header_other" => "",
"wpml_style" => true,
"header_buttons" => "auth=1|search=1|wishlist=1|cart=1|custom=0",
"header_top_background_color" => "#ffffff",
"header_top_color" => "#181818",
"header_top_accent_color" => "#C6AD8A",
"top_menu_depth" => "unlim",
"top_menu_submenu_color" => "#000000",
"top_menu_submenu_bg_color" => "#FFFFFF",
"top_menu_submenu_accent_color" => "",
"top_menu_submenu_layout" => "fullwidth",
"top_menu_font_size" => 14,
"top_menu_item_space" => 20,
"sticky_menu_desktop" => true,
"sticky_logo_desktop_hide" => false,
"sticky_logo_desktop_size" => "105",
"sticky_logo_desktop_hide_text" => "",
"header_type_mobile" => "header-type-mobile-1",
"header_logo_centered_mobile" => false,
"header_buttons_mobile" => "search=1|auth=1|wishlist=1|cart=1|custom=0",
"bottom_buttons_mobile_locations" => "menu",
"bottom_buttons_mobile" => "search=1|auth=1|wishlist=1|cart=1|custom=0",
"mobile_header_background_color" => "#FFFFFF",
"mobile_header_color" => "#000000",
"header_height_mobile" => 60,
"sticky_menu_mobile" => true,
"sticky_header_height_mobile" => 60,
"sticky_logo_mobile_hide" => false,
"custom_header_button_title" => "",
"custom_header_button_link" => "",
"custom_header_button_new_window" => false,
"custom_header_button_no_follow" => false,
"transparent_header" => false,
"transparent_header_color" => "",
"transparent_header_accent_color" => "",
"remove_frontpage_logo_link" => true,
"is_font_icons_loader_on" => "ideapark_font_icons_loader_plugin_on",
"truncate_logo_placeholder" => true,
"logo_size" => 205,
"logo_size_mobile" => 205,
"ajax_search_post_type" => "products",
"ajax_search" => true,
"ajax_search_limit" => 8,
"header_advert_bar_page" => 0,
"header_advert_bar_placement" => "below",
"facebook" => "",
"instagram" => "",
"vk" => "",
"ok" => "",
"telegram" => "",
"whatsapp" => "",
"line" => "",
"wechat" => "",
"viber" => "",
"discord" => "",
"twitter" => "",
"youtube" => "",
"vimeo" => "",
"snapchat" => "",
"tiktok" => "",
"linkedin" => "",
"flickr" => "",
"pinterest" => "",
"tumblr" => "",
"github" => "",
"custom_soc_url_1" => "",
"custom_soc_url_2" => "",
"post_layout" => "list",
"remove_post_breadcrumbs" => false,
"post_grid_list_hide_category" => false,
"post_grid_list_hide_date" => false,
"post_grid_list_hide_excerpt" => false,
"sidebar_post" => true,
"post_hide_category" => false,
"post_hide_date" => false,
"post_hide_share" => false,
"post_hide_tags" => false,
"post_hide_comment" => false,
"post_hide_author" => false,
"post_hide_postnav" => false,
"text_color" => "#181818",
"accent_color" => "#C6AD8A",
"accent_background_color" => "#FDF9F2",
"shadow_color_desktop" => "#FFFFFF",
"hide_inner_background" => true,
"footer_page" => 0,
"footer_copyright" => "&copy; Copyright 2022, Goldish WordPress Theme",
"theme_font_text" => "Jost",
"theme_font_subsets" => "latin-ext",
"capitalize_headers" => true,
"is_metabox_on" => "ideapark_metabox_plugin_on",
"header_breadcrumbs" => true,
"sticky_sidebar" => true,
"disable_elementor_default_gap" => true,
"disable_block_editor" => true,
"limit_fullwidth_1920" => true,
"share_buttons" => "facebook=1|twitter=1|pinterest=1|whatsapp=1|telegram=0|linkedin=0",
"to_top_button" => false,
"to_top_button_color" => "#C6AD8A",
"use_minified_css" => true,
"use_minified_js" => true,
"load_jquery_in_footer" => true,
"lazyload" => true,
"google_fonts_display_swap" => true,
"js_delay" => true,
"popup_cart_layout" => "default",
"popup_cart_auto_open_desktop" => false,
"popup_cart_auto_open_mobile" => false,
"popup_cart_modal" => false,
"cart_auto_update" => false,
"expand_coupon" => false,
"store_notice" => "top",
"store_notice_button_hide" => false,
"store_notice_button_text" => "",
"store_notice_color" => "#FFFFFF",
"store_notice_background_color" => "#CF3540",
"disable_purchase" => false,
"hide_prices" => false,
"search_by_sku" => true,
"search_by_category" => false,
"search_by_tag" => false,
"hide_uncategorized" => true,
"hidden_product_category" => 0,
"register_page" => 0,
"maintenance_mode_page" => 0,
"products_per_page" => 12,
"product_grid_pagination" => "pagination",
"product_grid_load_more_text" => "Load More",
"show_subcat_in_header" => false,
"show_subcat_in_header_nav" => false,
"subcat_in_header_layout" => "round",
"shop_sidebar" => true,
"single_sidebar" => false,
"shop_sidebar_modal" => false,
"product_grid_layout" => "4-per-row",
"product_grid_text_desktop" => "below",
"product_grid_width" => "fullwidth",
"product_buttons_layout" => "buttons-2",
"product_grid_layout_mobile" => "1-per-row-mobile",
"product_grid_text_mobile" => "below-mobile",
"wishlist_grid_button" => true,
"shop_modal" => true,
"hide_add_to_cart_mobile_2_per_row" => false,
"hide_add_to_cart_mobile_compact" => false,
"shop_category" => true,
"show_add_to_cart" => true,
"product_short_description" => true,
"short_description_link" => true,
"product_preview_rating" => true,
"product_preview_number" => false,
"star_rating_color" => "#FFBB54",
"show_color_variations" => false,
"hide_single_color_variations" => false,
"color_variations_size" => 16,
"is_swatches_on" => "ideapark_swatches_plugin_on",
"category_description_position" => "below",
"product_font_size" => 24,
"product_font_size_compact" => 18,
"grid_image_fit" => "cover",
"grid_image_prop" => 1,
"switch_image_on_hover" => true,
"quickview_product_zoom" => false,
"quickview_product_zoom_mobile_hide" => false,
"is_woocommerce_on" => "ideapark_woocommerce_on",
"product_page_layout" => "layout-1",
"product_category_carousel" => false,
"remove_product_breadcrumbs" => false,
"product_page_blocks_layout-1" => "ideapark_product_page_blocks_order",
"product_page_blocks_layout-2" => "ideapark_product_page_blocks_order",
"product_page_blocks_layout-3" => "ideapark_product_page_blocks_order",
"product_gallery_layout" => "desktop",
"product_summary_background_color" => "#FDF9F2",
"product_tabs_layout" => "tabs-compact",
"product_tabs" => "description=1|additional_information=1|reviews=1",
"description_tab_header" => "",
"additional_information_tab_header" => "",
"additional_tab_layout" => "inline",
"expand_tab_mobile" => false,
"expand_first_tab" => false,
"product_share" => true,
"hide_variable_price_range" => false,
"hide_stock_info" => false,
"hide_sku" => false,
"sticky_add_to_cart" => false,
"product_page_ajax_add_to_cart" => false,
"product_video_position" => 4,
"product_bottom_page" => 0,
"product_page_font_size_desktop" => 45,
"product_page_font_size_mobile" => 40,
"product_image_fit" => "cover",
"product_image_prop" => 1,
"product_image_background_color" => "#F7F7F7",
"shop_product_modal" => true,
"product_inline_video" => true,
"shop_product_zoom" => false,
"shop_product_zoom_mobile_hide" => false,
"product_page_custom_html" => "",
"product_html_text_color" => "",
"product_html_background_color" => "",
"product_html_border" => false,
"product_html_border_color" => "",
"product_html_2_col" => false,
"product_features_text_color" => "",
"product_features_description_color" => "",
"product_features_background_color" => "",
"product_features_border" => true,
"product_features_border_color" => "",
"is_shop_configured" => "ideapark_is_shop_configured",
"shop_html_block_top" => 0,
"shop_html_block_bottom" => 0,
"shop_html_block_first_page" => false,
"shop_top_block_above" => false,
"show_product_grid_brand" => false,
"show_product_page_brand" => false,
"hide_brand_additional_tab" => false,
"show_product_page_brand_logo" => true,
"show_cart_page_brand" => false,
"search_by_brand" => false,
"brands_page" => 0,
"outofstock_badge_color" => "",
"outofstock_badge_text" => "Out of stock",
"featured_badge_color" => "",
"featured_badge_text" => "Featured",
"sale_badge_color" => "",
"sale_badge_text" => "Разпродажба",
"sale_badge_layout" => "percentage",
"new_badge_color" => "",
"new_badge_text" => "New",
"product_newness" => 5,
"wishlist_page" => 0,
"wishlist_share" => true,
"related_product_show" => true,
"related_product_number" => 4,
"related_product_header" => "",
"upsells_product_header" => "",
"cross_sells_product_header" => "",
"related_grid_layout" => "default",
"hide_related_short_description" => false,
"recently_enabled" => false,
"recently_product_number" => 4,
"recently_product_show" => false,
"recently_shop_show" => false,
"recently_cart_show" => false,
"recently_product_header" => "",
"recently_position" => "above",
"recently_grid_layout" => "default",
"hide_recently_short_description" => false,
"last_option" => "",
];

global $ideapark_customize_mods_names;
$ideapark_customize_mods_names = [
"0" => "header_top_bar_settings_info",
"1" => "header_type",
"2" => "header_blocks_1",
"3" => "header_blocks_2",
"4" => "header_phone",
"5" => "header_email",
"6" => "header_address",
"7" => "header_hours",
"8" => "header_lang",
"9" => "header_other",
"10" => "wpml_style",
"11" => "header_desktop_settings_info",
"12" => "header_buttons",
"13" => "custom_button_info_1",
"14" => "wishlist_is_disabled",
"15" => "header_top_background_color",
"16" => "header_top_color",
"17" => "header_top_accent_color",
"18" => "top_menu_depth",
"19" => "top_menu_submenu_color",
"20" => "top_menu_submenu_bg_color",
"21" => "top_menu_submenu_accent_color",
"22" => "top_menu_submenu_layout",
"23" => "top_menu_font_size",
"24" => "top_menu_item_space",
"25" => "sticky_menu_desktop",
"26" => "sticky_logo_desktop_hide",
"27" => "sticky_logo_desktop_size",
"28" => "sticky_logo_desktop_hide_text",
"29" => "header_mobile_settings_info",
"30" => "header_type_mobile",
"31" => "header_logo_centered_mobile",
"32" => "header_buttons_mobile",
"33" => "custom_button_info_2",
"34" => "bottom_buttons_mobile_locations",
"35" => "bottom_buttons_mobile",
"36" => "custom_button_info_3",
"37" => "mobile_header_background_color",
"38" => "mobile_header_color",
"39" => "header_height_mobile",
"40" => "sticky_menu_mobile",
"41" => "sticky_header_height_mobile",
"42" => "sticky_logo_mobile_hide",
"43" => "custom_header_button_info",
"44" => "custom_header_icon_desc_0",
"45" => "custom_header_button_icon",
"46" => "custom_header_button_title",
"47" => "custom_header_button_link",
"48" => "custom_header_button_new_window",
"49" => "custom_header_button_no_follow",
"50" => "transparent_header_settings_info",
"51" => "transparent_header",
"52" => "transparent_header_color",
"53" => "transparent_header_accent_color",
"54" => "logo_sticky",
"55" => "logo_mobile_sticky",
"56" => "header_other_settings_info",
"57" => "remove_frontpage_logo_link",
"58" => "custom_header_icons_info",
"59" => "custom_header_icon_desc",
"60" => "custom_header_icon_search",
"61" => "custom_header_icon_auth",
"62" => "custom_header_icon_wishlist",
"63" => "custom_header_icon_cart",
"64" => "custom_header_icon_hamburger",
"65" => "is_font_icons_loader_on",
"66" => "header_desktop_logo_info",
"67" => "logo",
"68" => "truncate_logo_placeholder",
"69" => "logo_size",
"70" => "header_mobile_logo_info",
"71" => "logo_mobile",
"72" => "logo_size_mobile",
"73" => "header_height_mobile_link",
"74" => "ajax_search_post_type",
"75" => "ajax_search",
"76" => "ajax_search_limit",
"77" => "header_advert_bar_page",
"78" => "header_advert_bar_placement",
"79" => "facebook",
"80" => "instagram",
"81" => "vk",
"82" => "ok",
"83" => "telegram",
"84" => "whatsapp",
"85" => "line",
"86" => "wechat",
"87" => "viber",
"88" => "discord",
"89" => "twitter",
"90" => "youtube",
"91" => "vimeo",
"92" => "snapchat",
"93" => "tiktok",
"94" => "linkedin",
"95" => "flickr",
"96" => "pinterest",
"97" => "tumblr",
"98" => "github",
"99" => "custom_soc_icon_1",
"100" => "custom_soc_url_1",
"101" => "custom_soc_icon_2",
"102" => "custom_soc_url_2",
"103" => "post_layout",
"104" => "remove_post_breadcrumbs",
"105" => "post_grid_list_hide_category",
"106" => "post_grid_list_hide_date",
"107" => "post_grid_list_hide_excerpt",
"108" => "sidebar_post",
"109" => "post_hide_category",
"110" => "post_hide_date",
"111" => "post_hide_share",
"112" => "post_hide_tags",
"113" => "post_hide_comment",
"114" => "post_hide_author",
"115" => "post_hide_postnav",
"116" => "text_color",
"117" => "accent_color",
"118" => "accent_background_color",
"119" => "shadow_color_desktop",
"120" => "hide_inner_background",
"121" => "footer_page",
"122" => "footer_copyright",
"123" => "theme_font_text",
"124" => "theme_font_subsets",
"125" => "capitalize_headers",
"126" => "header_custom_fonts_info",
"127" => "header_custom_fonts_reload",
"128" => "is_metabox_on",
"129" => "header_breadcrumbs",
"130" => "sticky_sidebar",
"131" => "disable_elementor_default_gap",
"132" => "disable_block_editor",
"133" => "limit_fullwidth_1920",
"134" => "404_empty_image",
"135" => "cart_empty_image",
"136" => "wishlist_empty_image",
"137" => "share_buttons",
"138" => "to_top_button_info",
"139" => "to_top_button",
"140" => "to_top_button_color",
"141" => "use_minified_css",
"142" => "use_minified_js",
"143" => "load_jquery_in_footer",
"144" => "lazyload",
"145" => "google_fonts_display_swap",
"146" => "js_delay",
"147" => "popup_cart_layout",
"148" => "popup_cart_auto_open_desktop",
"149" => "popup_cart_auto_open_mobile",
"150" => "popup_cart_modal",
"151" => "cart_auto_update",
"152" => "expand_coupon",
"153" => "expand_coupon_info",
"154" => "store_notice_info",
"155" => "store_notice",
"156" => "store_notice_button_hide",
"157" => "store_notice_button_text",
"158" => "store_notice_color",
"159" => "store_notice_background_color",
"160" => "disable_purchase",
"161" => "hide_prices",
"162" => "search_by_sku",
"163" => "search_by_category",
"164" => "search_by_tag",
"165" => "search_by_brand_info",
"166" => "hide_uncategorized",
"167" => "hidden_product_category",
"168" => "register_page",
"169" => "maintenance_mode_page",
"170" => "products_per_page",
"171" => "product_grid_pagination",
"172" => "product_grid_load_more_text",
"173" => "show_subcat_in_header",
"174" => "show_subcat_in_header_nav",
"175" => "subcat_in_header_layout",
"176" => "shop_sidebar",
"177" => "single_sidebar",
"178" => "shop_sidebar_modal",
"179" => "product_grid_layout",
"180" => "product_grid_text_desktop",
"181" => "product_grid_width",
"182" => "product_buttons_layout",
"183" => "product_grid_layout_mobile",
"184" => "product_grid_text_mobile",
"185" => "wishlist_grid_button",
"186" => "shop_modal",
"187" => "hide_add_to_cart_mobile_2_per_row",
"188" => "hide_add_to_cart_mobile_compact",
"189" => "shop_category",
"190" => "show_add_to_cart",
"191" => "product_short_description",
"192" => "short_description_link",
"193" => "product_preview_rating",
"194" => "product_preview_number",
"195" => "star_rating_color",
"196" => "show_color_variations",
"197" => "hide_single_color_variations",
"198" => "product_color_attribute",
"199" => "color_variations_size",
"200" => "is_swatches_on",
"201" => "category_description_position",
"202" => "product_font_size",
"203" => "product_font_size_compact",
"204" => "grid_image_info",
"205" => "grid_image_fit",
"206" => "grid_image_prop",
"207" => "switch_image_on_hover",
"208" => "quickview_product_zoom",
"209" => "quickview_product_zoom_mobile_hide",
"210" => "is_woocommerce_on",
"211" => "product_page_layout",
"212" => "product_category_carousel",
"213" => "remove_product_breadcrumbs",
"214" => "product_page_blocks_layout-1",
"215" => "product_page_blocks_layout-2",
"216" => "product_page_blocks_layout-3",
"217" => "product_page_blocks_reload",
"218" => "product_gallery_layout",
"219" => "product_summary_background_color",
"220" => "product_tabs_layout",
"221" => "product_tabs",
"222" => "description_tab_header",
"223" => "additional_information_tab_header",
"224" => "additional_tab_layout",
"225" => "expand_tab_mobile",
"226" => "expand_first_tab",
"227" => "product_share",
"228" => "hide_variable_price_range",
"229" => "hide_stock_info",
"230" => "hide_sku",
"231" => "sticky_add_to_cart",
"232" => "product_page_ajax_add_to_cart",
"233" => "product_video_position",
"234" => "product_bottom_page",
"235" => "product_page_font_size_desktop",
"236" => "product_page_font_size_mobile",
"237" => "product_image_info",
"238" => "product_image_fit",
"239" => "product_image_prop",
"240" => "product_image_background_color",
"241" => "shop_product_modal",
"242" => "product_inline_video",
"243" => "shop_product_zoom",
"244" => "shop_product_zoom_mobile_hide",
"245" => "product_page_custom_html_info",
"246" => "product_page_custom_html",
"247" => "product_html_text_color",
"248" => "product_html_background_color",
"249" => "product_html_border",
"250" => "product_html_border_color",
"251" => "product_html_2_col",
"252" => "product_features_info",
"253" => "product_features_icon_desc",
"254" => "product_features_text_color",
"255" => "product_features_description_color",
"256" => "product_features_background_color",
"257" => "product_features_border",
"258" => "product_features_border_color",
"259" => "is_shop_configured",
"260" => "shop_is_not_configured",
"261" => "shop_html_block_top",
"262" => "shop_html_block_bottom",
"263" => "shop_html_block_first_page",
"264" => "shop_top_block_above",
"265" => "product_brand_attribute",
"266" => "show_product_grid_brand",
"267" => "show_product_page_brand",
"268" => "hide_brand_additional_tab",
"269" => "show_product_page_brand_logo",
"270" => "show_cart_page_brand",
"271" => "search_by_brand",
"272" => "brands_page",
"273" => "outofstock_badge_info",
"274" => "outofstock_badge_color",
"275" => "outofstock_badge_text",
"276" => "featured_badge_info",
"277" => "featured_badge_color",
"278" => "featured_badge_text",
"279" => "sale_badge_info",
"280" => "sale_badge_color",
"281" => "sale_badge_text",
"282" => "sale_badge_layout",
"283" => "new_badge_info",
"284" => "new_badge_color",
"285" => "new_badge_text",
"286" => "product_newness",
"287" => "wishlist_page",
"288" => "wishlist_share",
"289" => "related_settings_info",
"290" => "related_product_show",
"291" => "related_product_number",
"292" => "related_product_header",
"293" => "upsells_product_header",
"294" => "cross_sells_product_header",
"295" => "related_grid_layout",
"296" => "hide_related_short_description",
"297" => "recently_settings_info",
"298" => "recently_enabled",
"299" => "recently_product_number",
"300" => "recently_product_show",
"301" => "recently_shop_show",
"302" => "recently_cart_show",
"303" => "recently_product_header",
"304" => "recently_position",
"305" => "recently_grid_layout",
"306" => "hide_recently_short_description",
"307" => "last_option",
];

global $ideapark_customize_mods_images;
$ideapark_customize_mods_images = [
"0" => "logo_sticky",
"1" => "logo_mobile_sticky",
"2" => "logo",
"3" => "logo_mobile",
"4" => "404_empty_image",
"5" => "cart_empty_image",
"6" => "wishlist_empty_image",
];

